name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6f6b5c78a7b5197419f7902f070ba482dfda99ef5c6e87326d7e43dc3dc19cc"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"
