name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.20.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f8defd2617d130a1f5447848cd57ec1bb5e9ce40fcc93bbc62496213609b8f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.4"
