name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.16.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00ac84a664351591551eb9842c1d519310495aa2bcf7b363b468f74d6c5f928c"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
