name = "Adrenaline"
author = "SkywardMC"
version = "26.2.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "062c84b82e501446b31c8aad59ff52293b8a36019aa1b40d9a137df81480a9b1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
