name = "Adrenaline"
author = "SkywardMC"
version = "26.3.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5187d38c6f815f7fc2c7c6ba5c3b4b74ccd2854a0fa81abc7b4c4edc65d4e302"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
