name = "Adrenaline"
author = "SkywardMC"
version = "26.2.0+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c102e9b199b26eab3a47f4df0030df31790c8361f461eb49d79c72d6ee125eb"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
