name = "Adrenaline"
author = "SkywardMC"
version = "26.2.0+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f375983f857778ccda22ec2b1fb7586b020b2b332368ae64c4adb730960500b9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
