name = "Adrenaline"
author = "SkywardMC"
version = "26.3.1+mc1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2147797fde5f903ee246fdf74fcf25a0204091d7366a054195a1f7a2e1f5094b"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
