name = "Adrenaline"
author = "SkywardMC"
version = "26.3.1+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f9222e8d24ba67a12fd26d6528ce90b054e165c85a16c3dd2dbf505ddfde1f"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
