name = "Adrenaline"
author = "SkywardMC"
version = "26.3.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47581fb659e750277a4a5428c475c9ccd77af2fb47ba986d4cce6b9d2cdd4c6e"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
