name = "Adrenaline"
author = "SkywardMC"
version = "26.3.0+mc26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "088bfccc527a820c4c8d3cee514ba7e55fc7d21af6b7086aad8363b32abd7f99"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
