name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f61a72c91b530e48f2a3e88ba55a1f8e9444f0002ff955cfed8e10c5cbb653"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
