name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d85e1324d2dbcc48c9cb178aa0209db94685a111962ba8c3f411816e9124f66"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
