name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cf01a445db023e707bb8a73538d0364d18e823775e9788ff143497f4655fa70"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
