name = "Adrenaline"
author = "SkywardMC"
version = "26.2.0+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df7a1b631903478d59fb670a133f25505d0e451da1f64f50ef30d3eb2127c4d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
