name = "Adrenaline"
author = "SkywardMC"
version = "26.1.5+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64f325b61835e47e8d06472d32ad66f01f29693b5c1fc0f167043f18a507bc98"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
