name = "Adrenaline"
author = "SkywardMC"
version = "26.3.0+mc1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8469ed07d5b4fa05b52ef93cf2f775587ac8817091f6f1a1a21d1a00a0332ee9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
