name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51b97d1c1d6b8b3d81d5ddd4c31ea8535db0ecc430618899d9c95d2369511e47"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
