name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1248034e35916bd52173381098bd6ba5542d4d4c3c0c066099a3c7fb82bce0ef"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
