name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19a9df37b48e34dbd7b99ddddd77534182de2c40425cc2ac44cb9008a0decc6a"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
