name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c002a54e4d584f37ecb20c9e453429edf73a769b268a51113631b20c33d5404"

[versions]
fabric = "0.18.5"
minecraft = "1.19.4"
