name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96491ba8a9526a62730b6b5b31fcdb9b468d88b8eaa3cdf4e09cfed2ccc55836"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
