name = "Adrenaline"
author = "SkywardMC"
version = "26.1+mc1.19.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b547bae83e6e3a6fcb3b4a03f4a01a81da9e23fd4d6c0a333e4dfa33bca6ea18"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
