name = "Adrenaline"
author = "SkywardMC"
version = "26.1.5+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c66eb0cf4601e6182eb48186b5e78e22146d313c49c35f572ded7408842ca772"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
