name = "Adrenaline"
author = "SkywardMC"
version = "26.3.0+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "853df89deaea9bcea47315fd8b69adb13ac968d862097f421911d89bd9be7bfe"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
