name = "Adrenaline"
author = "SkywardMC"
version = "26.2.0+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438212d38b5874a34e2ceaf149bb3f71e081f189001c66279a0d81373c90e7e2"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
